POST http://localhost:7878/api/participant/add
Content-Type: application/json

{
    "counter_id": "1",
    "queue_code": "A011",
    "name": "Atikah Jaya Kusuma Anggraini Simanjuntak Butar Butar",
    "phone_number": "6285765627679"
}
